### ISSUE TITLE
sorry for general questions

### ISSUE THREAD

**Issue by ganesh1997oli** [haodev007/first_azero_contract#2]
are you from alephzero chain?

**Comment by tofuwu-dev** [comment]
> are you from alephzero chain?

Yes, I am but just beginning

**Comment by ganesh1997oli** [comment]
can you share any means of your communication?

**Comment by tofuwu-dev** [comment]
> can you share any means of your communication?

use Telegram?
@haodev_007

**Comment by ganesh1997oli** [comment]
are you on discord?

**Comment by tofuwu-dev** [comment]
> 

will be on there. sec

**Comment by tofuwu-dev** [comment]
> are you on discord?

plz check sc-support channel of AZero

**Comment by ganesh1997oli** [comment]
are you available there?
